// Graphs
export const LOAD_GRAPH_SUCCESS = 'LOAD_GRAPH_SUCCESS';

// Articles
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLE_SUCCESS = 'LOAD_ARTICLE_SUCCESS';

// Dictionary types
export const ADD_DICTIONARY_TYPE = 'ADD_DICTIONARY_TYPE';
export const REMOVE_DICTIONARY_TYPE = 'REMOVE_DICTIONARY_TYPE';

// Layout type
export const SET_LAYOUT = 'SET_LAYOUT';

// Centrality sort
export const SELECT_CENTRALITY_SORT = 'SELECT_CENTRALITY_SORT';