export const DICTIONARY_TYPES = {
	NOUN : "N",
	VERB : "V",
	ADJECTIVE : "A",
	PRONOUN : "P",
	ADVERB : "R",
	ADPOSITION : "S",
	CONJUCTION : "C",
	NUMERAL : "M",
	PARTICLE : "Q",
	INTERJECTION : "I",
	ABBRECIATION : "Y",
	RESIDUAL : "X",
	PUNCTUATION : "Z"
}